engines:
  duplication:
    enabled: true
    config:
      languages:
      - python

plugins:
  pep8:
    enabled: true
    checks:
      E231:
        enabled: false
      E402:
        enabled: false
      E501:
        enabled: false

  radon:
    enabled: true

  fixme:
    enabled: true
    
  markdownlint:
    enabled: true
    

ratings:
  paths:
  - "pypdnsrest/*.py"

exclude_paths:
  - "tests/"
  - "tests_integration/"
