dist: trusty
sudo: required

language: python

services:
  - docker

cache:
    pip: true
    directories:
        - $HOME/.cache/pip
        - .tox

matrix:
    include:
        - python: 3.5
          env: TOXENV=py35
        - python: 3.5
          env: TOXENV=py3-cover,coverage
        - python: 3.5
          env: TOXENV=pep8
        - python: 3.6-dev
          env: TOXENV=py36
        - python: nightly
          env: TOXENV=py37
    allow_failures:
        - env: TOXENV=py36
        - env: TOXENV=py37
        - env: TOXENV=py3-cover,coverage

before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log

before_script:
    - sudo apt-get -qq update

before_install:
  - docker pull raspi/docker-powerdns-travis-ci-rest-test
  - docker run --network host --detach raspi/docker-powerdns-travis-ci-rest-test
  - sudo netstat --listening --protocol inet --numeric

install:
  - travis_retry pip install tox

script:
  - travis_retry tox

after_sucess:
  - pip install codeclimate-test-reporter
  - codeclimate-test-reporter
