language: python
sudo: false

cache:
    pip: true
    directories:
        - $HOME/.cache/pip
        - .tox

before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log

matrix:
    include:
        - python: 3.5
          env: TOXENV=py35
        - python: 3.5
          env: TOXENV=py3-cover,coverage
        - python: 3.5
          env: TOXENV=pep8
        - python: 3.6-dev
          env: TOXENV=py36
        - python: nightly
          env: TOXENV=py37
    allow_failures:
        - env: TOXENV=py36
        - env: TOXENV=py37
        - env: TOXENV=py3-cover,coverage

install:
  - travis_retry pip install tox

script:
  - travis_retry tox